name: A workflow for my Hello World file
on:
  schedule:
    - cron: "0 3 * * *" # every 12:00 JST
  workflow_dispatch:
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
