name: A workflow for my Hello World file
on:
  workflow_dispatch:
  schedule:
    - cron: "5/5 3 * * *" # every 12:00 JST
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
